### ISSUE TITLE
Remove direct edit access to the wiki

### ISSUE THREAD

**Issue by kensykora** [PowerShell/xCertificate#102]
I don't think I should have direct edit access to the wiki. I was expecting to create a pull request for the wiki fix, but it let me edit it directly instead. You probably need to fix permissions here.

**Comment by PlagueHO** [comment]
Hi @kwirkykat - are you able to prevent direct editing of the Wiki for this repo (and xStorage, xNetworking and xDFS) to collaborators only as @kensykora suggested?

@kensykora - thanks for pointing this out. Were you needing to edit the front page or one of the "Resource" pages? The resource pages are all automatically generated so you'd not want to edit those, but instead submit a PR to change the resource MOF or Examples or README.ME files.

**Comment by kensykora** [comment]
I made this edit here: https://github.com/PowerShell/xCertificate/wiki/xPfxImport/_compare/3ac2f675611b2d0a3382d2ee72590dd6f5be4093

Thanks for this module, it works great!

**Comment by johlju** [comment]
>By default, only collaborators on your repository can make changes to wikis, but you can configure this to be enabled for all users on public repositories.
https://help.github.com/articles/about-github-wikis/

I guess "Restrict edits to collaborators only" should be selected, [Changing access permissions for wikis](https://help.github.com/articles/changing-access-permissions-for-wikis).

**Comment by PlagueHO** [comment]
Thanks @kensykora ! Great catch on the edit too - I'll need to submit a PR to get this fixed in this repo itself though because this file is generated automatically every time the resource kit is released. So your correction would be reverted. I'll raise an issue and submit a PR.

**Comment by PlagueHO** [comment]
I have submitted the PR to fix this in the main repo: #104

**Comment by kwirkykat** [comment]
@PlagueHO Updated the setting for the wiki. Can you check that you can still edit it before I change it on the other repos as well?

**Comment by PlagueHO** [comment]
@kwirkykat - I can still edit OK! @johlju - could you do a quick negative test to ensure you _can't_ edit the Wiki anymore?

**Comment by johlju** [comment]
I don't have write access to the wiki. So it seems it works. :)

**Comment by PlagueHO** [comment]
Awesome! Thanks @Johlju. @kwirkykat, I think you can go ahead and make the same change to the other repos. I'll close this issue now.
