### ISSUE TITLE
Set Github Repository Title

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xCertificate#115]
@kwirkykat - can you set the Github repository title for this repo to:
This DSC Resource module can be used to simplify administration of certificates on a Windows Server.

Is it also worth setting the website to something like: https://blogs.msdn.microsoft.com/powershell/tag/dsc-resource-kit/

Or to the main DSC Resource Kit repo on Github?

Thank you!

**Comment by kwirkykat** [comment]
@PlagueHO Done

**Comment by PlagueHO** [comment]
Awesome! Thanks @kwirkykat
