### ISSUE TITLE
Invalid Thumbprint error

### ISSUE THREAD

**Issue by braahyan** [PowerShell/xCertificate#17]
I was unable to use the xPfxImport to import a certificate. It was giving me an error message that my hash was invalid. I used the same hash and certificate with the import-pfxcertificate cmdlet and it worked fine. If there is any more information that I can supply, let me know, I'd like to avoid using the script resources for this if I can.

**Comment by briantist** [comment]
@braahyan if you could include the error text that would be great. Does the PFX contain the private key? if not, could I get a copy of it? If you don't want to post it publicly, my email is my first name @ my domain (check my profile). Thanks!
