### ISSUE TITLE
Store not being set to WebHosting

### ISSUE THREAD

**Issue by PaulSpn1** [PowerShell/xCertificate#18]
Hello,

I have set the Store to WebHosting and its still importing into Personal store the debug info confirms its going into Cert:\LocalMachine\My. 

Paul

**Comment by briantist** [comment]
@PaulSpn1 is IIS installed? The `WebHosting` store doesn't exist before IIS is installed so it may just take an invalid store and use `My` as the default (if so that would be the `Import-PfxCertificate` cmdlet doing that, not this resource).

**Comment by PaulSpn1** [comment]
Yes IIS is installed and Default website exists

**Comment by PaulSpn1** [comment]
The verbose output is below, so its seems to still think the sore is set as My, event iff I specify a different store the output remains the same

VERBOSE: [PMDEV]:                            [[xPfxImport]CompanyCert] Performing the operation "Set-TargetResource" on target "Importin
g PFX 'C:\Certs\wildcard 02092014 2016.pfx' into 'Cert:\LocalMachine\My'".

**Comment by DdenBraver** [comment]
@PaulSpn1 Could you please tell me which store it is you are trying to write to?
This way I can try to recreate the issue.

**Comment by DdenBraver** [comment]
@PaulSpn1 Could you please try this action again with the latest version of the resource?
If you are still running into the same issue, Please let me know what parameters you are using (without the certificate/thumbprint) and I will see if I can recreate the issue.

**Comment by PlagueHO** [comment]
I'm going to close this one because of lack of activity. @PaulSpn1 - feel free to reopen this.
