### ISSUE TITLE
[New Feature] Extend xCertReq to Support additional Parameters

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xCertificate#25]
At the company I work for we're going to be needing some additional features in this resource:
1. TemplateName - the name of the CA template to use.
2. KeyLength - the request is set to 1024 - should be defineable.
3. Exportable - Defaults to True, but this should be definable.
4. ProviderName - Should allow selection - KSP is recommended when using SHA-2. CSP is currently only option.
5. OID - should be able to override this.
6. KeyUsage - should be able to override this.

Would there be any objections to us adding these features and submitting them to this resource over the next few weeks?

**Comment by johlju** [comment]
Looks like this are improvements many would benefit from. Love to see a PR for this so the PowerShell Team can review and merge.

**Comment by PlagueHO** [comment]
@johlju - cool! Thanks for the feedback! Appreciate it. I'll help some of my team put together the changes and get the PR submitted over the next week or two.

**Comment by PlagueHO** [comment]
Unfortunately this resource module is quite far behind the current DSC standards (HQRM). So I'll need to bring it up to up to this level at the same time as making the changes.
