### ISSUE TITLE
[New Resource] xPfxExport

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xCertificate#26]
User Story: Need to be able to use certificates that are either already in the Windows Certificate Mahine Store (or have been requested via xCertReq) in software that does not use the Windows Certificate Store to store certificates. An example is Java Key Store (JKS) files.

This would require a certificate to be found in the machine store (via Thumbprint, Subject, Serial Number, KU, Issuer etc) and then exported to a file (if the file does not exist), encrypting with a password or user/group combination (for Windows Server 2012+).

Export of the Private key would only be able to occur if it was available and exportable for the certificate identified for export.

If no one else is working on this I'll look at getting this one implemented (if there are no objections).

**Comment by johlju** [comment]
No PR's currently for review and no other open issues regarding this. So I say, go for it. Sounds like a great addition.
Great idea @PlagueHO

**Comment by PlagueHO** [comment]
Thanks @johlju  - I'll get this done.

**Comment by PlagueHO** [comment]
I'm going to close this issue because it will get rolled into #41.
