### ISSUE TITLE
xCertReq throws timeout error but successfully retrieves certificate?

### ISSUE THREAD

**Issue by GoGus85** [PowerShell/xCertificate#37]
I'm trying to use xCertReq to request an SSL certificate from my CA. I'm actually getting a strange timeout value in the end but I'm not sure why, and if I look in C:\Windows\Temp I can actually find the requested certificate there and it appears to be correctly issued and OK. See attached error. Why is it attempting to request a certificate using a new process when one was already requested just previously?
![certerror](https://cloud.githubusercontent.com/assets/23071782/20929522/b473500a-bbca-11e6-85ff-b665eda239d8.jpg)

**Comment by PlagueHO** [comment]
Hi @GoGus85 - thanks for reporting this.

Just a couple of questions to help me figure this one out:
1. Do you know which version of the xCertificate resource you're using?
2. Are you setting the credential parameter in the xCertReq?

There was a bug in 2.1.0.0 that did result in similar behavior to this.

**Comment by GoGus85** [comment]
Hello @PlagueHO,
Yes I'm running 2.2.0.0.
Yes I am, when I neglected to do so it failed earlier in the chain.

Looking in C:\windows\temp I have 5 files generated:
xCertReq*.inf
xCertReq.*req
xCertReq*.cer
xCertReq*.out
xCertReq*.rsp

The out file which is part of the statement thats throwing the error contains:
RequestId: 1001
RequestId: "1001"
Certificate retrieved(Issued) Issued

**Comment by PlagueHO** [comment]
Hi @GoGus85 - I'll take a look at this over the next couple of days and see if I can figure out what is going on. Are you able to post a copy of your config (with any sensitive information removed)?

**Comment by GoGus85** [comment]
The only parts that are related are these. Could it be because I'm only importing one of the resources rather than the complete module?

Import-DscResource -Name MSFT_xCertReq

        # Acquire certificate
        xCertReq SslCertificate
        {
            Subject = $Node.NodeName
            CAServerFQDN = "cafqdn"
            CARootName = "carootname"
            Credential = $GenericCredential
        }

**Comment by PlagueHO** [comment]
Hi @GoGus85 - it is possible this is a problem. Could you try importing the entire Module?

**Comment by GoGus85** [comment]
Well that fixed the issue...Thanks for the help!
