### ISSUE TITLE
xCertReq friendly name?

### ISSUE THREAD

**Issue by wasabii** [PowerShell/xCertificate#44]
Would be nice to be able to specify this. I want to create the cert, but later I want to use the name in another task or script. Nothing to key off of otherwise.

**Comment by PlagueHO** [comment]
@wasabii - thanks for raising this. This sounds like a great idea to me. It should be a reasonably minor change too.

**Comment by PlagueHO** [comment]
@wasabii - I'll have a go at adding this over the weekend.

**Comment by PlagueHO** [comment]
Hi @wasabii - sorry about taking so long. But I've completed this change now. It is in the Dev branch and will be released in a few weeks. Feel free to try this now and let me know if you have any problems.
