### ISSUE TITLE
Import fails on 2008 R2 because Import-PfxCertificate utility does not exist on Win 2008 R2

### ISSUE THREAD

**Issue by plraustin** [PowerShell/xCertificate#46]
Import fails on 2008 R2 because Import-PfxCertificate PS utility / command does not exist on Win 2008 R2

**Comment by PlagueHO** [comment]
Hi @plraustin - thanks for logging this. There probably is a solution to this using something like certutil.exe to perform the import instead of the Import-PfxCertificate cmdlet. I'll look into this when I get time (unless someone else gets to this first).

**Comment by rodolfosalgado** [comment]
any update on this ?

**Comment by PlagueHO** [comment]
Hi @rodolfosalgado - the change for this actually got submitted here: https://github.com/PowerShell/xCertificate/pull/55

However it was never completed. I plan to pick this up and complete it but I've not had time yet.

**Comment by PlagueHO** [comment]
I might try and get to this one tomorrow if I have time.
