### ISSUE TITLE
xCertReq does not confirm that SubjectAltName is correct

### ISSUE THREAD

**Issue by SeanEGray** [PowerShell/xCertificate#61]
xCertReq's Test-TargetResource returns true if the certificate is found but SubjectAltName is incorrect. It should return false if SubjectAltName is incorrect.

**Comment by SeanEGray** [comment]
PR 62 created to fix: https://github.com/PowerShell/xCertificate/pull/62

**Comment by PlagueHO** [comment]
This has been closed because PR #62 was merged. Thanks @SeanEGray !
