### ISSUE TITLE
space in CARootName break the submit

### ISSUE THREAD

**Issue by TLaborde** [PowerShell/xCertificate#67]
It seems there was a PR rolled back on that subject, bu I have a similar issue, my root cert contains space, and the certreq -submit fails because of it. Is there a quickfix on that matter?

edit : i'm on 2.6.0.0, and it doesn't look like it's related to the 2.5.0.0 fix

**Comment by PlagueHO** [comment]
Hi @TLaborde - Have you tried 2.7.0.0? Also, could you post your config and error log if possible?

Are you referring to either of these two fixes?
https://github.com/PowerShell/xCertificate/issues/42
https://github.com/PowerShell/xCertificate/issues/49

**Comment by TLaborde** [comment]
Just tried on 2.7.0.0, same issue.
Yeah i was referring to #42 

the config:

```
xCertReq SSLCert {
    Subject = 'dev-sso.mycompany.com'
    AutoRenew = $false
    CARootName = 'MyCompany IT Sites CA City'
    CAServerFQDN = 'rcassc.mycompany.com'
    Credential = $Creds
    CertificateTemplate = "MyCompany-Sites-Common"
    KeyUsage = 0
    ProviderName = '"Microsoft RSA SChannel Cryptographic Provider"'
    KeyLength = 2048
    SubjectAltName = "DNS=dev-sso.mycompany.com"
}
```

Related logs and error:
```
VERBOSE: [DEVADFS001]:                            [[xCertReq]SSLCert] Set-TargetResource: Submitting certificate request 'C:\Windows\TEMP\xCertReq-92a9233b-0ab0-448a-9edc-b2e83b78f028.req' returning 'C:\Windows\TEMP\xCertReq-92a9233b-0ab0-448a-9edc-b2e83b78f028.cer' issued by rcassc.mycompany.com\MyCompany IT Sites CA City.
VERBOSE: [DEVADFS001]:                            [[xCertReq]SSLCert] Set-TargetResource: Submitting certificate request result: RequestId: 1408
VERBOSE: [DEVADFS001]: LCM:  [ End    Set      ]  [[xCertReq]SSLCert]  in 0.6100 seconds.
PowerShell DSC resource MSFT_xCertReq  failed to execute Set-TargetResource functionality with error message: Certificate file 
'C:\Windows\TEMP\xCertReq-92a9233b-0ab0-448a-9edc-b2e83b78f028.cer' not found. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : devadfs001
```

It does generate a rsp file, but not the .cer
If i run the certreq command from the host in powershell with the req file, it works.

I also tried using PsDscRunAsCredential and even after giving the account the proper local rights, I get the same error.

**Comment by TLaborde** [comment]
Nevermind, it was a credential right issue...

**Comment by TLaborde** [comment]
Just if someone else have a similar problem, i looked into the CA logs to find more info on what happen.
