### ISSUE TITLE
xCertReq randomly fails with error "RPC server is unavailable"

### ISSUE THREAD

**Issue by Yvand** [PowerShell/xCertificate#73]
Hello,
I have reliability issues with xCertReq on Windows Server 2016: randomly (about 1 every 10 times), it fails with error "The RPC server is unavailable. 0x800706ba (WIN32: 1722 RPC_S_SERVER_UNAVAILABLE)".
I use it in a DC hosted in Azure that gets deployed from scratch, below is the relevant portion:
```powershell
WindowsFeature AddCertAuthority       { Name = "ADCS-Cert-Authority"; Ensure = "Present"; DependsOn = "[xPendingReboot]Reboot1" }
WindowsFeature AddADCSManagementTools { Name = "RSAT-ADCS-Mgmt";      Ensure = "Present"; DependsOn = "[xPendingReboot]Reboot1" }
xADCSCertificationAuthority ADCS
{
	Ensure = "Present"
	Credential = $DomainCredsNetbios
	CAType = "EnterpriseRootCA"
	DependsOn = "[WindowsFeature]AddCertAuthority"
}

xCertReq ADFSSiteCert
{
	CARootName                = "$DomainNetbiosName-$ComputerName-CA"
	CAServerFQDN              = "$ComputerName.$DomainFQDN"
	Subject                   = "$ADFSSiteName.$DomainFQDN"
	KeyLength                 = '2048'
	Exportable                = $true
	ProviderName              = '"Microsoft RSA SChannel Cryptographic Provider"'
	OID                       = '1.3.6.1.5.5.7.3.1'
	KeyUsage                  = '0xa0'
	CertificateTemplate       = 'WebServer'
	AutoRenew                 = $true
	#SubjectAltName            = "certauth.$ADFSSiteName.$DomainFQDN"
	Credential                = $DomainCredsNetbios
	DependsOn = '[xADCSCertificationAuthority]ADCS'
}
```

Here is the full execution of the resource, with the error:
```
[[xCertReq]ADFSSiteCert]
VERBOSE: [2017-06-20 12:21:08Z] [VERBOSE] [DC]: LCM:  [ Start  Test     ]  
[[xCertReq]ADFSSiteCert]
VERBOSE: [2017-06-20 12:21:08Z] [VERBOSE] [DC]:                            
[[xCertReq]ADFSSiteCert] Test-TargetResource: Testing Certificate with Subject 
'CN=ADFS.contoso.local' issued by DC.contoso.local\contoso-DC-CA.
VERBOSE: [2017-06-20 12:21:08Z] [VERBOSE] [DC]:                            
[[xCertReq]ADFSSiteCert] Test-TargetResource: No valid certificate found with 
subject 'CN=ADFS.contoso.local' issued by DC.contoso.local\contoso-DC-CA.
VERBOSE: [2017-06-20 12:21:08Z] [VERBOSE] [DC]: LCM:  [ End    Test     ]  
[[xCertReq]ADFSSiteCert]  in 0.0630 seconds.
VERBOSE: [2017-06-20 12:21:08Z] [VERBOSE] [DC]: LCM:  [ Start  Set      ]  
[[xCertReq]ADFSSiteCert]
VERBOSE: [2017-06-20 12:21:08Z] [VERBOSE] [DC]:                            
[[xCertReq]ADFSSiteCert] Set-TargetResource: Starting Certificate request with 
Subject 'ADFS.contoso.local' issued by DC.contoso.local\contoso-DC-CA.
VERBOSE: [2017-06-20 12:21:08Z] [VERBOSE] [DC]:                            
[[xCertReq]ADFSSiteCert] Set-TargetResource: Creating certificate request 
'C:\Windows\TEMP\xCertReq-479eb889-ebef-46bc-a56c-3fc0e1449657.req' from 
'C:\Windows\TEMP\xCertReq-479eb889-ebef-46bc-a56c-3fc0e1449657.inf'.
VERBOSE: [2017-06-20 12:21:09Z] [VERBOSE] [DC]:                            
[[xCertReq]ADFSSiteCert] Set-TargetResource: Create certificate request result:
 Active Directory Enrollment Policy
VERBOSE: [2017-06-20 12:21:09Z] [VERBOSE] [DC]:                            
[[xCertReq]ADFSSiteCert] Set-TargetResource: Submitting certificate request 
'C:\Windows\TEMP\xCertReq-479eb889-ebef-46bc-a56c-3fc0e1449657.req' returning 
'C:\Windows\TEMP\xCertReq-479eb889-ebef-46bc-a56c-3fc0e1449657.cer' issued by 
DC.contoso.local\contoso-DC-CA.
VERBOSE: [2017-06-20 12:21:09Z] [VERBOSE] [DC]:                            
[[xCertReq]ADFSSiteCert] Set-TargetResource: Submitting certificate request 
using separate process.
VERBOSE: [2017-06-20 12:21:10Z] [VERBOSE] [DC]:                            
[[xCertReq]ADFSSiteCert] Set-TargetResource: Submitting certificate request 
result: Certificate Request Processor: The RPC server is unavailable.
0x800706ba (WIN32: 1722 RPC_S_SERVER_UNAVAILABLE)
VERBOSE: [2017-06-20 12:21:10Z] [VERBOSE] [DC]: LCM:  [ End    Set      ]  
[[xCertReq]ADFSSiteCert]  in 2.3780 seconds.
VERBOSE: [2017-06-20 12:21:10Z] [ERROR] PowerShell DSC resource MSFT_xCertReq  
failed to execute Set-TargetResource functionality with error message: 
Certificate file 
'C:\Windows\TEMP\xCertReq-479eb889-ebef-46bc-a56c-3fc0e1449657.cer' not found.
```

Additional information:
- When LCM runs config again, xCertReq always completes successfully
- DSC config has other xCertReq that run just after this one and they seem to be always successful, even when this one fails

Could it occur because I run xCertReq just after xADCSCertificationAuthority?
Do you have any idea of a possible workaround? I'm thinking about testing a timer between xADCSCertificationAuthority and xCertReq but I don't know if it's relevant.

**Comment by PlagueHO** [comment]
Hi @Yvand - thanks for submitting this issue - great detail. I do wonder if the request is hitting the ADCS before is has completed installing and the service has started.

Perhaps I could create a new resource to wait for the ADCS to have started up (with a timeout etc). Similar to the xWaitForDisk resources in xStorage.

I'll do some investigation and see if there is a way of detecting if an ADCS is available without connecting to it.

**Comment by Yvand** [comment]
Hi @PlagueHO on my side I implemented a 30 secs timer between xADCSCertificationAuthority and xCertReq and since then I never faced this issue again, so it looks like it's indeed because ADCS is randomly not ready yet when xCertReq runs.

**Comment by PlagueHO** [comment]
Hi @Yvand - I'll see about creating a new resource that will wait for the ADCS to become available. It shouldn't be too difficult. I'll see if I can put it together this weekend.

**Comment by Yvand** [comment]
Hi @PlagueHO it would be really great, but I wonder if it should be a separate resource, or a logic implemented directly in xCertReq resource? Or Both?

**Comment by PlagueHO** [comment]
Hi @Yvand - I'm mainly basing that on other patterns we've implemented similar behavior in a separate resource. For example: in [xStorage](https://github.com/PowerShell/xStorage) we have the xWaitForDisk and xWaitForVolume.

This reduces complexity of the resource and makes it usable outside xCertReq.

We'd want to use a similar pattern here as well - something like this:
```
[ClassVersion("1.0.0.0"), FriendlyName("xWaitForCA")]
class MSFT_xWaitForCA : OMI_BaseResource
{
    [Write, Description("The type of CA in use, Standalone/Enterprise.")] String CAType;
    [Write, Description("The FQDN of the Active Directory Certificate Authority on the local area network. Leave empty to automatically locate.")] String CAServerFQDN;
[Write, Description("The name of the certificate authority, by default this will be in format domain-servername-ca. Leave empty to automatically locate.")] String CARootName;
    [Write, Description("Specifies the number of seconds to wait for the CA to become available.")] Uint32 RetryIntervalSec;
    [Write, Description("The number of times to loop the retry interval while waiting for the CA.")] Uint32 RetryCount;
};
```
What do you think? Would this address the problem?

**Comment by Yvand** [comment]
Hi @PlagueHO I understand, this makes sense.
Yes the resource looks great, I'm eager to test it :)

**Comment by PlagueHO** [comment]
Hi @Yvand - I've completed this resource and submitted a PR for it. It may take a little while to get this PR reviewed and merged, so feel free to try out the version in my branch: https://github.com/PlagueHO/xCertificate/tree/Issue-73

**Comment by Yvand** [comment]
Hi @PlagueHO yesterday I tested your PR and it worked fine in my environment, thank you very much for this!

**Comment by PlagueHO** [comment]
Hi @Yvand - awesome! That is great to know!

FYI: We changed the name of the resource to xWaitForCertificateServices - so once this has been released you'll need to change your configs to use the new name. Sorry about that - we're trying to avoid using abbreviations in names now.
