### ISSUE TITLE
Enable Wiki on Github Repo

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xCertificate#96]
**Details of the scenario you tried and the problem that is occurring:**
The Wiki is not enabled on the xCertificate repo. I need this to be enabled because this repo is now auto-documentation enabled.

@kwirkykat or @zjalexander - can either of you please turn this on in the repo for me? Thank you

**The DSC configuration that is using the resource (as detailed as possible):**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
N/A

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
N/A

**Comment by kwirkykat** [comment]
@PlagueHO Done
